language: cpp

compiler:
  - clang

sudo: required
dist: trusty

before_install:
  - echo $LANG
  - echo $LC_ALL

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
  - cpack --config CPackConfig.cmake
